#!/bin/bash
#PBS -P CLIPSensorEncoding
#PBS -q volta_gpu
#PBS -l select=1:ncpus=5:ngpus=1
#PBS -j oe
#PBS -N CLIPSensorEncodingRun1

cd $PBS_O_WORKDIR;
np=$(cat ${PBS_NODEFILE} | wc -l);

module load singularity
image="/app1/common/singularity-img/3.0.0/pytorch_2.0_cuda_12.0_cudnn8-devel_u22.04.sif"
# image="/app1/common/singularity-img/hopper/pytorch/pytorch_2.4.0a0-cuda_12.5.0_ngc_24.06.sif"


echo "Running on $(hostname) with $np cores and $CUDA_VISIBLE_DEVICES GPUs";

# cd /hpctmp/e0268113/CLIP
# singularity exec $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID

#     python /hpctmp/e0268113/CLIP/benchmark.py

# EOF



# for i in 1024 512 256 128 64 32 16;
# do
#     echo "Running on $(hostname) with GPU $i";
#     singularity exec $image bash << EOF >> stdout.$PBS_JOBID 2>> stderr.$PBS_JOBID
    
#     python train.py --dataset_root='/home/svu/e0268113/datasets/flickr8k' \
#                     --save_checkpoint_dir='/hpctmp/e0268113/checkpoints' \
#                     --load_checkpoint_path='/hpctmp/e0268113/checkpoints/ViT-B-32.pt' \
#                     --train_batch_size=$i \
#                     --training_epochs=10
# EOF
# done

# singularity exec $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID

# python train.py --dataset_root='/hpctmp/e0268113/datasets/flickr8k' \
#                 --save_checkpoint_dir='/hpctmp/e0268113/checkpoints' \
#                 --load_checkpoint_path='/hpctmp/e0268113/checkpoints/ViT-B-32.pth' \
#                 --train_batch_size=128 \
#                 --training_epochs=16

# EOF

# singularity exec $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID

# python train.py --dataset_root='/home/svu/e0268113/datasets/flickr8k' \p
#                 --save_checkpoint_dir='/hpctmp/e0268113/checkpoints' \
#                 --train_batch_size=256 \
#                 --training_epochs=30

# EOF

# singularity exec $image bash python train.py --dataset_root='/home/svu/e0268113/datasets/flickr8k' \
#                 --save_checkpoint_dir='/hpctmp/e0268113/checkpoints' \
#                 --load_checkpoint_path='/hpctmp/e0268113/checkpoints/ViT-B-32.pt' \
#                 --train_batch_size=128 \
#                 --training_epochs=16

# EOF

# singularity exec $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID

# cd /hpctmp/e0268113/datasets

# /home/svu/e0268113/.local/bin/img2dataset --url_list mscoco.parquet \
#                                          --input_format "parquet"  \
#                                          --url_col "URL" \
#                                          --caption_col "TEXT" \
#                                          --output_format webdataset \
#                                          --output_folder mscoco \
#                                          --processes_count 16 \
#                                          --thread_count 64 \
#                                          --image_size 256  \
#                                          --enable_wandb True

# EOF


